bank/urls.py
from django.conf.urls import url
from . import views

app_name = 'bank'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^add$', views.add_word, name='add_word'),
	url(r'^backup$', views.backup, name='backup'),
	url(r'^backupXML$', views.backupXML, name='backupXML'),
	url(r'^upload$', views.uploadCSV, name='uploadCSV'),
	url(r'^loadCSV/(?P<activity>\w+)$', views.loadCSV, name='loadCSV'),
	url(r'^loadXML/(?P<activity>\w+)$', views.loadXML, name='loadXML'),
	url(r'^clear$', views.clear, name='clear'),
	url(r'^list$', views.word_list, name='word_list'),
	url(r'^lastest$', views.lastest_search, name='lastest_search'),
	url(r'^freq$', views.freq_search, name='freq_search'),
	url(r'^detail/(?P<word>\w+)$', views.word_detail, name='word_detail'),
	url(r'^search$', views.word_search, name='word_search')
]

word_bank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bank.urls')),
    url(r'^admin/', admin.site.urls),
]

bank/models.py
from django.db import models

class Word(models.Model):
	word_text = models.CharField(max_length=50)
	def __str__(self):
		return self.word_text

class Mean(models.Model):
	word = models.ForeignKey(Word,on_delete=models.CASCADE)
	word_type = models.CharField(max_length=50)
	word_mean = models.CharField(max_length=300)
	word_ex = models.CharField(max_length=300)
	def __str__(self):
		return self.word_mean

class Search(models.Model):
	search_text = models.CharField(max_length=50)
	search_time = models.DateTimeField('date published')
	search_count = models.IntegerField(default=1)
	def __str__(self):
		return self.search_text

bank/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.files import File
from django.core.files.storage import default_storage
from django.utils import timezone
import os,csv
from xml.etree.ElementTree import Element, SubElement
from xml.etree.ElementTree import ElementTree as ET
import xml.etree.ElementTree
from lxml import etree

from .models import Word,Mean,Search

def home(request):
	time_search_list = Search.objects.order_by('-search_time')[:5]
	freq_search_list = Search.objects.order_by('-search_count')[:5]
	context = {'time_search_list':time_search_list,'freq_search_list':freq_search_list}
	return render(request,'home.html',context)

def add_word(request):
	#try-except for 1st request with empty post data
	try:
		word = request.POST['word']
		word_type = request.POST['word_type']
		word_mean = request.POST['word_mean']
		word_ex = request.POST['word_ex']
	except:
		return render(request, 'add.html')
	word_list = Word.objects.order_by('word_text')
	try:
		w = Word.objects.get(word_text=word)
	except:
		w = Word(word_text=word)
		w.save()
	w.mean_set.create(word_type=word_type,word_mean=word_mean,word_ex=word_ex)
	return HttpResponseRedirect(reverse('bank:word_list'))

def backup(request):
	csv_file = "bank/backup/backup.csv"
	word_list = Word.objects.all()
	with open(csv_file, 'w') as file:
		write = csv.writer(file, delimiter=',')
		for word in word_list:
			for mean in word.mean_set.all():
				data = [[word.word_text,mean.word_type,mean.word_mean,mean.word_ex]]
				write.writerows(data)
	return HttpResponseRedirect(reverse('bank:word_list'))

def backupXML(request):
	xml_file = "bank/backup/backup.xml"
	word_list = Word.objects.all()
	bank = Element('bank')
	for word in word_list:
		for mean in word.mean_set.all():
			w = SubElement(bank, 'word')
			te = SubElement(w, 'text')
			te.text = word.word_text
			ty = SubElement(w, 'type')
			ty.text = mean.word_type
			me = SubElement(w, 'mean')
			me.text = mean.word_mean
			ex = SubElement(w, 'ex')
			ex.text = mean.word_ex
	ET(bank).write(xml_file)
	f = open(xml_file)
	text = f.read()
	f.close()
	f = open(xml_file, 'w')
	f.write('<!DOCTYPE bank SYSTEM "std.dtd">')
	f.write(text)
	f.close()
	f = open('bank/static/backup.xml', 'w')
	f.write('<!DOCTYPE bank SYSTEM "std.dtd">')
	f.write(text)
	f.close()
	return HttpResponseRedirect(reverse('bank:word_list'))

def clear(request):
	word_list = Word.objects.all()
	for word in word_list:
		word.delete()
	return HttpResponseRedirect(reverse('bank:word_list'))

def loadCSV(request,activity):
	if activity == 'restore':
		csv_file = "bank/backup/backup.csv"
	elif activity == 'upload':
		csv_file = "bank/uploadTemp/upload.csv"
	dataReader = csv.reader(open(csv_file))
	temp_text = ''
	for row in dataReader:
		if row[0] != 'word_text':
			if row[0] != '':
				word_text = row[0]
				temp_text = row[0]
			else:
				word_text = temp_text
			word_type = row[1]
			word_mean = row[2]
			word_ex = row[3]
			try:
				w = Word.objects.get(word_text=word_text)
			except:
				w = Word(word_text=word_text)
				w.save()
			w.save()
			w.mean_set.create(word_type=word_type,word_mean=word_mean,word_ex=word_ex)
	return HttpResponseRedirect(reverse('bank:word_list'))

def loadXML(request,activity):
	if activity == 'restore':
		xml_file = "bank/backup/backup.xml"
	elif activity == 'upload':
		xml_file = "bank/uploadTemp/upload.xml"
	try:
		parser = etree.XMLParser(dtd_validation=True)
		tree = etree.parse(xml_file, parser)
	except:
		return HttpResponse('Error, Invalid XML.')
	bank = xml.etree.ElementTree.parse(xml_file)
	root = bank.getroot()
	for word in root.findall('word'):
		word_text = word.find('text').text
		word_type = word.find('type').text
		word_mean = word.find('mean').text
		word_ex = word.find('ex').text
		try:
			w = Word.objects.get(word_text=word_text)
		except:
			w = Word(word_text=word_text)
			w.save()
		w.save()
		w.mean_set.create(word_type=word_type,word_mean=word_mean,word_ex=word_ex)
	return HttpResponseRedirect(reverse('bank:word_list'))

def uploadCSV(request):
	path = 'bank/uploadTemp/'
	if request.FILES != {}:
		file = request.FILES['uploadedFile']
		filename = file.name
		if filename.endswith('.csv'):
			savePath = default_storage.save(path,file)
			os.rename(savePath,'{}upload.csv'.format(path))
			return HttpResponseRedirect(reverse('bank:loadCSV', args=('upload',)))
		elif filename.endswith('.xml'):
			savePath = default_storage.save(path,file)
			os.rename(savePath,'{}upload.xml'.format(path))
			return HttpResponseRedirect(reverse('bank:loadXML', args=('upload',)))
		else:
			return HttpResponseRedirect(reverse('bank:add_word'))
	else:
		return HttpResponseRedirect(reverse('bank:add_word'))

def word_list(request):
	word_list = Word.objects.order_by('word_text')
	context = {'word_list':word_list}
	return render(request, 'list.html', context)

def word_detail(request,word):
	word = Word.objects.get(word_text=word)
	context = {'word':word}
	return render(request, 'detail.html', context)

def word_search(request):
	text = request.POST['text']
	method = request.POST['method']
	#############################################################################################
	try:
		s = Search.objects.get(search_text=text)
		s.search_time = timezone.now()
		s.search_count += 1
		s.save()
	except:
		s = Search(search_text=text,search_time=timezone.now(),search_count=1)
		s.save()
	#############################################################################################
	if method == 'startswith':
		word_list = Word.objects.filter(word_text__startswith=text)
	elif method == 'endswith':
		word_list = Word.objects.filter(word_text__endswith=text)
	else:
		word_list = Word.objects.filter(word_text__contains=text)
	context = {'text':text,'method':method,'word_list':word_list}
	return render(request, 'search.html', context)

def lastest_search(request):
	search_list = Search.objects.order_by('-search_time')[:]
	context = {'search_list':search_list}
	return render(request, 'lastest.html', context)

def freq_search(request):
	search_list = Search.objects.order_by('-search_count')[:]
	context = {'search_list':search_list}
	return render(request, 'freq.html', context)

bank/templates/add.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>Add Word</title>
</head>
<body>
<div>
<h3>Add Word</h3>
{% if text %}{{ text }}{% endif %}
<form action="{% url 'bank:add_word' %}" method="post">
{% csrf_token %}
Word: <input type="text" name="word" value="{{ word }}" pattern="[A-Za-z]+" id="max_box" required>
<select name="word_type">
	{% if word_type %}<option value="{{ word_type }}">{{ word_type }}</option>{% endif %}
	<option value="nouns">nouns</option>
	<option value="verbs">verbs</option>
	<option value="adjective">adjective</option>
	<option value="adverbs">adverbs</option>
	<option value="pronouns">pronouns</option>
	<option value="connective">connective</option>
</select><br>
Meaning: <input type="text" name="word_mean" value="{{ word_mean }}" id="max_box" required><br>
Example: <input type="text" name="word_ex" value="{{ word_ex }}" id="max_box" required><br>
<input type="submit" value="Submit">
</form>
<h3>Batch add Word</h3>
<form action="{% url 'bank:uploadCSV' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<input type="file" name="uploadedFile" id="uploadedFile" required>
	<input type="submit" value="Batch add">
</form>
<form action="{% url 'bank:home' %}" method="get">
	<input type="submit" value="Home">
	<input type="submit" value="Word list" formaction="{% url 'bank:word_list' %}">
</form>
</div>
</body>
</html>

bank/templates/detail.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
	<title>Word Detail: {{ word.word_text }}</title>
</head>
<body>
<div>
<h3><p>Word Detail: {{ word.word_text }}</p></h3>
	<table background-color=gray border="0">
		<tr>
			<td bgcolor="#AAAAAA" colspan="3"><a href="{% url 'bank:word_detail' word.word_text %}">{{ word.word_text }}</a></td>
		</tr>
		{% for mean in word.mean_set.all %}
		<tr>
			<td bgcolor="#DFDFDF" width="120">{{ mean.word_type }}</td>
			<td bgcolor="#DFDFDF" width="500">{{ mean.word_mean }}</td>
			<td bgcolor="#DFDFDF" width="300">{{ mean.word_ex }}</td>
		</tr>
		{% endfor %}
	</table>
<br><form action="{% url 'bank:home' %}" method="get">
	<input type="submit" value="Home">
	<input type="submit" value="Word list" formaction="{% url 'bank:word_list' %}">
</form>
</div>
</body>
</html>

bank/templates/freq.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
	<title>Frequency search list</title>
</head>
<body>
<div>
<h3><p>Frequency search list</p></h3>
	{% if search_list %}
	<p>
	<table background-color=gray border="0" id="table" width="500px">
	<tr>
		<td bgcolor="#7A7A7A"><b>search phase</b></td>
		<td bgcolor="#7A7A7A"><b>search time</b></td>
		<td bgcolor="#7A7A7A"><b>count</b></td>
	</tr>
	{% for search in search_list %}
		<tr>
			<td bgcolor="#AAAAAA">
				<form action="{% url 'bank:word_search' %}" method="post" name="search_form">
				{% csrf_token %}
					<input type="text" name="text" value="{{ search }}" hidden required>
					<input type="text" name="method" hidden required>
					<a href="javascript:;" onclick="parentNode.submit();">{{ search }}</span> 
				</form>
			</td>
			<td bgcolor="#AAAAAA">{{ search.search_time }}</td>
			<td bgcolor="#AAAAAA">{{ search.search_count }}</td>
		</tr>
	{% endfor %}
	</table>
	</p>
	{% else %}
		<p>No lastest search list available.</p>
	{% endif %}
<form action="{% url 'bank:home' %}" method="get">
	<input type="submit" value="Home">
</form>
</div>
</body>
</html>

bank/templates/home.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>Word Bank</title>
</head>
<body>
<div class=home>
<h3>Word Bank</h3>
<form action="{% url 'bank:word_search' %}" method="post">
{% csrf_token %}
	Search: <input type="text" name="text" id="half_box" required>
	<select name="method" id="select_box">
		<option value="contains">Contains</option>
		<option value="startswith">Startswith</option>
		<option value="endswith">Endswith</option>
	</select>
	<input type="submit" value="Search">
</form>
<form action="{% url 'bank:word_list' %}" method="get">
	<input type="submit" value="Word list">
	<input type="submit" value="Add Word" formaction="{% url 'bank:add_word' %}">
	<input type="submit" value="Lastest search" formaction="{% url 'bank:lastest_search' %}">
	<input type="submit" value="Frequency search" formaction="{% url 'bank:freq_search' %}">
</form>
<table width="1100px" align="center">
<tr>
<td>
<h3><p align="center">5 Lastest search list</p></h3>
	{% if time_search_list %}
	<p>
	<table background-color=gray border="0" id="table" width="500px" align="center">
	<tr>
		<td bgcolor="#7A7A7A"><b>search phase</b></td>
		<td bgcolor="#7A7A7A"><b>search time</b></td>
		<td bgcolor="#7A7A7A"><b>count</b></td>
	</tr>
	{% for search in time_search_list %}
		<tr>
			<td bgcolor="#AAAAAA">
				<form action="{% url 'bank:word_search' %}" method="post" name="search_form">
				{% csrf_token %}
					<input type="text" name="text" value="{{ search }}" hidden required>
					<input type="text" name="method" hidden required>
					<a href="javascript:;" onclick="parentNode.submit();">{{ search }}</span> 
				</form>
			</td>
			<td bgcolor="#AAAAAA">{{ search.search_time }}</td>
			<td bgcolor="#AAAAAA">{{ search.search_count }}</td>
		</tr>
	{% endfor %}
	</table>
	</p>
	{% else %}
		<p>No lastest search list available.</p>
	{% endif %}
</td>
<td>
<h3><p align="center">5 Frequency search list</p></h3>
	{% if freq_search_list %}
	<p>
	<table background-color=gray border="0" id="table" width="500px" align="center">
	<tr>
		<td bgcolor="#7A7A7A"><b>search phase</b></td>
		<td bgcolor="#7A7A7A"><b>search time</b></td>
		<td bgcolor="#7A7A7A"><b>count</b></td>
	</tr>
	{% for search in freq_search_list %}
		<tr>
			<td bgcolor="#AAAAAA">
				<form action="{% url 'bank:word_search' %}" method="post" name="search_form">
				{% csrf_token %}
					<input type="text" name="text" value="{{ search }}" hidden required>
					<input type="text" name="method" hidden required>
					<a href="javascript:;" onclick="parentNode.submit();">{{ search }}</span> 
				</form>
			</td>
			<td bgcolor="#AAAAAA">{{ search.search_time }}</td>
			<td bgcolor="#AAAAAA">{{ search.search_count }}</td>
		</tr>
	{% endfor %}
	</table>
	</p>
	{% else %}
		<p>No lastest search list available.</p>
	{% endif %}
</td>
</tr>
</table>
</div>
</body>
</html>

bank/templates/lastest.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
	<title>Lastest search list</title>
</head>
<body>
<div>
<h3><p>Lastest search list</p></h3>
	{% if search_list %}
	<p>
	<table background-color=gray border="0" id="table" width="500px">
	<tr>
		<td bgcolor="#7A7A7A"><b>search phase</b></td>
		<td bgcolor="#7A7A7A"><b>search time</b></td>
		<td bgcolor="#7A7A7A"><b>count</b></td>
	</tr>
	{% for search in search_list %}
		<tr>
			<td bgcolor="#AAAAAA">
				<form action="{% url 'bank:word_search' %}" method="post" name="search_form">
				{% csrf_token %}
					<input type="text" name="text" value="{{ search }}" hidden required>
					<input type="text" name="method" hidden required>
					<a href="javascript:;" onclick="parentNode.submit();">{{ search }}</span> 
				</form>
			</td>
			<td bgcolor="#AAAAAA">{{ search.search_time }}</td>
			<td bgcolor="#AAAAAA">{{ search.search_count }}</td>
		</tr>
	{% endfor %}
	</table>
	</p>
	{% else %}
		<p>No lastest search list available.</p>
	{% endif %}
<form action="{% url 'bank:home' %}" method="get">
	<input type="submit" value="Home">
</form>
</div>
</body>
</html>

bank/templates/list.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
	<title>Word list</title>
</head>
<body>
<div>
<h3><p>Word list</p></h3>
<form action="{% url 'bank:word_search' %}" method="post">
{% csrf_token %}
	Search: <input type="text" name="text" id="max_box" required>
	<select name="method">
		<option value="contains">Contains</option>
		<option value="startswith">Startswith</option>
		<option value="endswith">Endswith</option>
	</select>
	<input type="submit" value="Search">
</form>
	{% if word_list %}
	<table background-color=gray border="0" id="table">
	{% for word in word_list %}
		<tr>
			<td bgcolor="#AAAAAA" colspan="3"><a href="{% url 'bank:word_detail' word.word_text %}">{{ word }}</a></td>
		</tr>
		{% for mean in word.mean_set.all %}
		<tr>
			<td bgcolor="#DFDFDF" width=10%>{{ mean.word_type }}</td>
			<td bgcolor="#DFDFDF" width=50%>{{ mean.word_mean }}</td>
			<td bgcolor="#DFDFDF" width=40%>{{ mean.word_ex }}</td>
		</tr>
		{% endfor %}
	{% endfor %}
	</table>
	{% else %}
		<p>No word available.</p>
	{% endif %}
<form action="{% url 'bank:backup' %}" method="get">
	<input type="submit" value="Backup CSV">
	<input type="submit" value="Backup XML" formaction="{% url 'bank:backupXML' %}">
	<input type="submit" value="Restore CSV" formaction="{% url 'bank:loadCSV' 'restore' %}">
	<input type="submit" value="Restore XML" formaction="{% url 'bank:loadXML' 'restore' %}">
	<input type="submit" value="Clear" formaction="{% url 'bank:clear' %}">
</form>
<p><a href="{% static 'backup.xml' %}" download><input type="submit" value="Download Backup XML"></a></p>
<form action="{% url 'bank:home' %}" method="get">
	<input type="submit" value="Home">
</form>
</div>
</body>
</html>

bank/templates/search.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
	<title>Word Search</title>
</head>
<body>
<div>
<h3><p>Word Search</p></h3>
<form action="{% url 'bank:word_search' %}" method="post">
{% csrf_token %}
	Search: <input type="text" name="text">
	<select name="method">
		<option value="contains">Contains</option>
		<option value="startswith">Startswith</option>
		<option value="endswith">Endswith</option>
	</select>
	<input type="submit" value="Search">
</form>
	You are searching "{{ text }}"<br>
	Search method: "{{ method }}"
	{% if word_list %}
	<table background-color=gray border="0">
	{% for word in word_list %}
		<tr>
			<td bgcolor="#AAAAAA" colspan="3"><a href="{% url 'bank:word_detail' word.word_text %}">{{ word.word_text }}</a></td>
		</tr>
		{% for mean in word.mean_set.all %}
		<tr>
			<td bgcolor="#DFDFDF" width="120">{{ mean.word_type }}</td>
			<td bgcolor="#DFDFDF" width="500">{{ mean.word_mean }}</td>
			<td bgcolor="#DFDFDF" width="300">{{ mean.word_ex }}</td>
		</tr>
		{% endfor %}
	{% endfor %}
	</table>
	{% else %}
		<p>No word match.</p>
	{% endif %}
<br><form action="{% url 'bank:home' %}" method="get">
	<input type="submit" value="Home">
</form>
</div>
</body>
</html>

bank/templates/text.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
	<title>Text</title>
</head>
<body>
<div>
<h3><p>Text</p></h3>
	{{ text }}
<br><a href="{% url 'bank:home' %}">Home</a>
</div>
</body>
</html>